import type { Meta, StoryObj } from '@storybook/react-vite';
import { Select } from './Select';
const options = ['Design system', 'Product', 'Engineering'];
const meta = { title: 'Components/Select', component: Select, tags: ['autodocs'], args: { label: 'Team', options } } satisfies Meta<typeof Select>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Overview: Story = {};
export const Variants: Story = { render: () => <div style={{ display: 'grid', gap: 20 }}><Select label="Single select" options={options} /><Select label="Required select" options={options} required /><Select label="Disabled select" options={options} disabled /></div> };
export const States: Story = { args: { defaultValue: 'Product', 'aria-invalid': true, 'aria-describedby': 'select-error' }, render: (args) => <div><Select {...args} /><span id="select-error" style={{ color: '#a51d35', display: 'block', fontSize: 12, marginTop: 6 }}>Choose a valid team.</span></div> };
export const Accessibility: Story = { args: { required: true } };
export const TokenDependencies: Story = { parameters: { docs: { description: { story: 'Uses color.text.primary, color.border.default, radius.medium, spacing.100, and typography.body.' } } } };