import type { Meta, StoryObj } from '@storybook/react-vite';
import { Tabs, type Tab } from './Tabs';
const tabs: Tab[] = [{ id: 'summary', label: 'Summary', content: 'A concise view of the current workspace.' }, { id: 'activity', label: 'Activity', content: 'Recent changes will appear here.' }, { id: 'settings', label: 'Settings', content: 'Manage workspace preferences.' }];
const meta = { title: 'Components/Tabs', component: Tabs, tags: ['autodocs'], args: { tabs } } satisfies Meta<typeof Tabs>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Overview: Story = {};
export const Variants: Story = { render: () => <div style={{ display: 'grid', gap: 32 }}><Tabs tabs={tabs.slice(0, 2)} /><Tabs tabs={tabs} defaultTab="settings" /></div> };
export const States: Story = { args: { defaultTab: 'activity' } };
export const Accessibility: Story = { parameters: { docs: { description: { story: 'Tabs use tablist, tab, and tabpanel semantics with an explicit active relationship.' } } } };
export const TokenDependencies: Story = { parameters: { docs: { description: { story: 'Uses color.text.primary, color.border.default, color.brand.primary, spacing.150, and typography.label.' } } } };