import type { Meta, StoryObj } from '@storybook/react-vite';
import { Input } from './Input';
const meta = { title: 'Components/Input', component: Input, tags: ['autodocs'], args: { label: 'Workspace name', placeholder: 'Enter a name' } } satisfies Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Overview: Story = {};
export const Variants: Story = { render: () => <div style={{ display: 'grid', gap: 20 }}><Input label="Default" placeholder="Optional value" /><Input label="With hint" hint="Use a name your team will recognize." placeholder="Project Atlas" /><Input label="Required" required placeholder="Required value" /></div> };
export const States: Story = { render: () => <div style={{ display: 'grid', gap: 20 }}><Input label="Disabled" disabled value="Unavailable" readOnly /><Input label="Error" error="Enter at least 3 characters." value="x" readOnly /></div> };
export const Accessibility: Story = { args: { label: 'Email address', type: 'email', required: true, hint: 'We use this for account notifications.' } };
export const TokenDependencies: Story = { parameters: { docs: { description: { story: 'Uses color.text.primary, color.border.default, radius.medium, spacing.100, and typography.body.' } } } };